const multer = require('.multer');
const { joi } = require('../util');
const { SplatfestResult } = require('../models/splatfest_result');

module.exports = {
	type: 'splatfest',
	result_model: SplatfestResult,
	validation_schema: joi.object({
		ServerEnv: joi.string(),
		PId: joi.numberstring(),
		MiiName: joi.string(),
		Model: joi.numberstring(),
		Skin: joi.numberstring(),
		EyeColor: joi.numberstring(),
		Weapon: joi.numberstring(),
		SumPaint: joi.numberstring(),
		Gear_Shoes: joi.numberstring(),
		Gear_Shoes_Skill0: joi.numberstring(),
		Gear_Shoes_Skill1: joi.numberstring(),
		Gear_Shoes_Skill2: joi.numberstring(),
		Gear_Clothes: joi.numberstring(),
		Gear_Clothes_Skill0: joi.numberstring(),
		Gear_Clothes_Skill1: joi.numberstring(),
		Gear_Clothes_Skill2: joi.numberstring(),
		Gear_Head: joi.numberstring(),
		Gear_Head_Skill0: joi.numberstring(),
		Gear_Head_Skill1: joi.numberstring(),
		Gear_Head_Skill2: joi.numberstring(),
		Rank: joi.numberstring(),
		Udemae: joi.numberstring(),
		RegularKillSum: joi.numberstring(),
		WinSum: joi.numberstring(),
		LoseSum: joi.numberstring(),
		TodaysCondition: joi.numberstring(),
		Region: joi.string(),
		Area: joi.numberstring(),
		FesID: joi.numberstring(),
		FesState: joi.numberstring(),
		FesTeam: joi.numberstring(),
		FesGrade: joi.numberstring(),
		FesPoint: joi.numberstring(),
		FesPower: joi.numberstring(),
		BestFesPower: joi.numberstring(),
		Money: joi.numberstring(),
		Shell: joi.numberstring(),
		TotalBonusShell: joi.numberstring(),
		MatchingTime: joi.numberstring(),
		IsRematch: joi.numberstring(),
		SaveDataCorrupted: joi.numberstring(),
		DisconnectedPId: joi.numberstring(),
		DisconnectedMemHash: joi.numberstring(),
		SessionID: joi.numberstring(),
		StartNetworkTime: joi.numberstring(),
		GameMode: joi.numberstring(),
		Rule: joi.numberstring(),
		Stage: joi.numberstring(),
		Team: joi.numberstring(),
		IsWinGame: joi.numberstring(),
		Kill: joi.numberstring(),
		Death: joi.numberstring(),
		Paint: joi.numberstring(),
		IsNetworkBurst: joi.numberstring(),
		BottleneckPlayerNum: joi.numberstring(),
		MaxSilenceFrame: joi.numberstring(),
		MemoryHash: joi.numberstring(),
		Paint_Alpha: joi.numberstring(),
		Paint_Bravo: joi.numberstring(),
		FaceImg: joi.binary()
	}).options({ presence: 'required' }).required(),
	multipart_validator: multer().fields([
		{ name: 'ServerEnv' },
		{ name: 'PId' },
		{ name: 'MiiName' },
		{ name: 'Model' },
		{ name: 'Skin' },
		{ name: 'EyeColor' },
		{ name: 'Weapon' },
		{ name: 'SumPaint' },
		{ name: 'Gear_Shoes' },
		{ name: 'Gear_Shoes_Skill0' },
		{ name: 'Gear_Shoes_Skill1' },
		{ name: 'Gear_Shoes_Skill2' },
		{ name: 'Gear_Clothes' },
		{ name: 'Gear_Clothes_Skill0' },
		{ name: 'Gear_Clothes_Skill1' },
		{ name: 'Gear_Clothes_Skill2' },
		{ name: 'Gear_Head' },
		{ name: 'Gear_Head_Skill0' },
		{ name: 'Gear_Head_Skill1' },
		{ name: 'Gear_Head_Skill2' },
		{ name: 'Rank' },
		{ name: 'Udemae' },
		{ name: 'RegularKillSum' },
		{ name: 'WinSum' },
		{ name: 'LoseSum' },
		{ name: 'TodaysCondition' },
		{ name: 'Region' },
		{ name: 'Area' },
		{ name: 'FesID' },
		{ name: 'FesState' },
		{ name: 'FesTeam' },
		{ name: 'FesGrade' },
		{ name: 'FesPoint' },
		{ name: 'FesPower' },
		{ name: 'BestFesPower' },
		{ name: 'Money' },
		{ name: 'Shell' },
		{ name: 'TotalBonusShell' },
		{ name: 'MatchingTime' },
		{ name: 'IsRematch' },
		{ name: 'SaveDataCorrupted' },
		{ name: 'DisconnectedPId' },
		{ name: 'DisconnectedMemHash' },
		{ name: 'SessionID' },
		{ name: 'StartNetworkTime' },
		{ name: 'GameMode' },
		{ name: 'Rule' },
		{ name: 'Stage' },
		{ name: 'Team' },
		{ name: 'IsWinGame' },
		{ name: 'Kill' },
		{ name: 'Death' },
		{ name: 'Paint' },
		{ name: 'IsNetworkBurst' },
		{ name: 'BottleneckPlayerNum' },
		{ name: 'MaxSilenceFrame' },
		{ name: 'MemoryHash' },
		{ name: 'Paint_Alpha' },
		{ name: 'Paint_Bravo' },
		{ name: 'FaceImg' }
	])
};